language: java
jdk: "-openjdk11"
branches:
  only:
    - master
before_install:
  - sudo apt-get install expect
  - openssl aes-256-cbc -K $encrypted_4ce98ce55cf7_key -iv $encrypted_4ce98ce55cf7_iv -in ./src/main/resources/application.properties.enc -out ./src/main/resources/application.properties -d
  - openssl aes-256-cbc -K $encrypted_85b38fbc9ce6_key -iv $encrypted_85b38fbc9ce6_iv -in ./src/main/resources/env/prd01/application-prd01.properties.enc -out ./src/main/resources/application-prd01.properties -d
  - openssl aes-256-cbc -K $encrypted_e08fbca97941_key -iv $encrypted_e08fbca97941_iv -in ./src/main/resources/env/prd02/application-prd02.properties.enc -out ./src/main/resources/application-prd02.properties -d
  - openssl aes-256-cbc -K $encrypted_45de953a4a46_key -iv $encrypted_45de953a4a46_iv -in deploy.sh.enc -out deploy.sh -d
  - chmod +x gradlew
  - chmod +x deploy.sh
  -
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$home/.gradle"
script: "./deploy.sh"
after_script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - dev.joongi@gmail.com